/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Bulldog3(props:any) {
  const { nodes, materials } = useGLTF("/models/bulldog3.gltf") as any;
  return (
    <group {...props} dispose={null}>
      <group position={[6.44, -34.03, -3.97]}>
        <group position={[-62.55, 34.03, 4.93]} rotation={[0, 0, Math.PI / 2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.KOLEC0.geometry}
            material={materials["p BLACK"]}
            position={[85.69, -59.82, 0]}
            rotation={[0, 0, 1.87]}
            scale={[1, -1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.KOLEC1.geometry}
            material={materials["p BLACK"]}
            position={[69.87, -29.85, 0]}
            rotation={[0, 0, 2.22]}
            scale={[1, -1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.KOLEC2.geometry}
            material={materials["p BLACK"]}
            position={[43.45, -8.91, 0]}
            rotation={[0, 0, 2.69]}
            scale={[1, -1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.KOLEC3.geometry}
            material={materials["p BLACK"]}
            position={[10.83, 0.31, 0]}
            rotation={[0, 0, 3.09]}
            scale={[1, -1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.KOLEC4.geometry}
            material={materials["p BLACK"]}
            position={[-22.74, -4.78, 0]}
            rotation={[-Math.PI, 0, -0.33]}
            scale={[1, -1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.KOLEC5.geometry}
            material={materials["p BLACK"]}
            position={[-52.07, -21.99, 0]}
            rotation={[-Math.PI, 0, -0.77]}
            scale={[1, -1, 1]}
          />
        </group>
        <group position={[16.44, 7.62, 3.97]}>
          <group position={[-2.05, 17.18, 2.19]} scale={37.31}>
            <group position={[0, 0.76, 0]}>
              <group position={[0.31, 0, -0.22]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_2.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[-0.06, 0, -0.22]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_3.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_1.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[-0.37, 0, -0.22]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_4.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_2.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[0.17, 0, -0.06]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_5.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_3.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[-0.02, 0, 0.04]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_6.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_4.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[-0.23, 0, -0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_7.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_5.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[0.45, 0, -0.08]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_8.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_6.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[0.34, 0, 0.1]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_9.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_7.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[0.16, 0, 0.22]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_10.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_8.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[-0.06, 0, 0.25]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_11.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_9.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[-0.27, 0, 0.19]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_12.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_10.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[-0.43, 0, 0.02]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_13.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_11.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
            </group>
            <group position={[0.02, -0.89, 0]}>
              <group position={[0.31, 0, -0.22]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_14.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_12.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[-0.06, 0, -0.22]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_15.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_13.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[-0.37, 0, -0.22]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_16.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_14.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[0.17, 0, -0.06]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_17.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_15.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[-0.02, 0, 0.04]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_18.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_16.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[-0.23, 0, -0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_19.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_17.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[0.43, 0, -0.1]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_20.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_18.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[0.33, 0, 0.07]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_21.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_19.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[0.16, 0, 0.22]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_22.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_20.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[-0.06, 0, 0.24]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_23.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_21.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[-0.25, 0, 0.13]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_24.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_22.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
            </group>
            <group position={[0, -0.04, 0]}>
              <group position={[0.31, 0, -0.22]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_25.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_23.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[-0.06, 0, -0.22]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_26.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_24.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[-0.37, 0, -0.22]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_27.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_25.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[0.17, 0, -0.06]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_28.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_26.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[-0.02, 0, 0.04]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_29.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_27.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[-0.23, 0, -0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_30.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_28.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[0.44, 0, -0.08]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_31.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_29.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[0.34, 0, 0.1]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_32.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_30.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[0.15, 0, 0.22]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_33.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_31.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[-0.06, 0, 0.24]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_34.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_32.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[-0.26, 0, 0.18]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_35.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_33.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
              <group position={[-0.43, 0, 0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BULDOG_36.geometry}
                  material={materials["alk BULDOG"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.ETYK_34.geometry}
                  material={materials["alk ETYK"]}
                  position={[0, 0.27, 0.08]}
                />
              </group>
            </group>
          </group>
          <group position={[-2.96, 48.43, -7.72]}>
            <group position={[0, -0.98, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["polka-p_BLACK"].geometry}
                material={materials["p BLACK"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["polka-LED"].geometry}
                material={materials.LED}
              />
            </group>
            <group position={[0, 0.98, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["LED-PLEXA"].geometry}
                material={materials.PLEXA}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["LED-LED"].geometry}
                material={materials.LED}
              />
            </group>
          </group>
          <group position={[-2.96, 18.5, -7.72]}>
            <group position={[0, -0.98, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["polka-p_BLACK_1"].geometry}
                material={materials["p BLACK"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["polka-LED_1"].geometry}
                material={materials.LED}
              />
            </group>
            <group position={[0, 0.98, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["LED-PLEXA_1"].geometry}
                material={materials.PLEXA}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["LED-LED_1"].geometry}
                material={materials.LED}
              />
            </group>
          </group>
          <group position={[-1.89, -12.86, -7.72]}>
            <group position={[0, -0.98, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["polka-p_BLACK_2"].geometry}
                material={materials["p BLACK"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["polka-LED_2"].geometry}
                material={materials.LED}
              />
            </group>
            <group position={[0, 0.98, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["LED-PLEXA_2"].geometry}
                material={materials.PLEXA}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["LED-LED_2"].geometry}
                material={materials.LED}
              />
            </group>
          </group>
        </group>
        <group position={[-27.48, 5.79, 6.83]}>
          <group position={[-6.29, 36.49, 4.22]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.logo_1.geometry}
              material={materials.LED}
            />
          </group>
          <group position={[21.04, 31.64, -3.49]}>
            <group position={[0, 0, 0.31]}>
              <group position={[36.07, -16.51, -7.04]}>
                <group position={[39.03, 16.51, 7.04]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.BUTELKA_4.geometry}
                    material={materials["LED violet"]}
                    position={[-35.93, -7.97, -7.95]}
                  />
                </group>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BUTELKA_1.geometry}
                  material={materials["PLEXA blue"]}
                  position={[-2.47, 8.54, -2.8]}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube.geometry}
                material={materials["LED violet"]}
                position={[75.11, 0, 0]}
              />
            </group>
            <group position={[0, 0, 3.56]}>
              <group position={[36.07, -16.51, -7.04]}>
                <group position={[39.03, 16.51, 7.04]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.BUTELKA_5.geometry}
                    material={materials["LED violet"]}
                    position={[-38.5, -7.97, -7.95]}
                  />
                </group>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BUTELKA_2.geometry}
                  material={materials["PLEXA blue"]}
                  position={[-2.47, 8.54, -2.8]}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube_1.geometry}
                material={materials["LED violet"]}
                position={[75.11, 0, 0]}
              />
            </group>
            <group position={[0, 0, -3.28]}>
              <group position={[36.07, -16.51, -7.04]}>
                <group position={[39.03, 16.51, 7.04]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.BUTELKA_6.geometry}
                    material={materials["LED violet"]}
                    // position={[-35.93, -7.97, -7.95]}
                    position={[-35.93, -7.97, 55.95]}
                  />
                </group>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.BUTELKA_3.geometry}
                  material={materials["PLEXA blue"]}
                  position={[-2.47, 8.54, -2.8]}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube_2.geometry}
                material={materials["LED violet"]}
                position={[75.11, 0, 0]}
              />
            </group>
          </group>
          <group
            position={[34.87, 34.83, -6.83]}
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group position={[-13.37, 2.52, -1.23]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["Boole1-BUTELKA"].geometry}
                material={materials["p BLACK"]}
                position={[26.75, 0.53, 2.47]}
              />
              <group position={[26.73, -4.24, 2.49]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes["Boole-BUTELKA"].geometry}
                  material={materials["p BLACK"]}
                />
              </group>
            </group>
            <group position={[13.37, -2.52, 1.23]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.KOLO_2.geometry}
                material={materials["LED violet"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.BUTELKA.geometry}
                material={materials["p BLACK"]}
                position={[6.4, 3.92, 9.93]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
            </group>
          </group>
        </group>
        <group position={[11.17, 34.98, -6.14]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["PLECY-p_BLACK"].geometry}
            material={materials["p BLACK"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["PLECY-p_BLACK_1"].geometry}
            material={materials["p BLACK"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["PLECY-LED_violet"].geometry}
            material={materials["LED violet"]}
          />
        </group>
        <group position={[-0.13, -48.39, -4.67]} rotation={[0, 1.57, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.PODSTAWA_2.geometry}
            material={materials["p BLACK"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.PODSTAWA1.geometry}
            material={materials["p BLACK"]}
            position={[0, 1.53, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.PODSTAWA_1.geometry}
            material={materials["LED violet"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/bulldog3.gltf");
