/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Human(props:any) {
  const { nodes, materials } = useGLTF("/models/human-stand.gltf") as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line014.geometry}
        material={materials["1"]}
        position={[-9.77, -0.05, -10.01]}
        rotation={[-3.05, 0.43, 3.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line015.geometry}
        material={materials["1"]}
        position={[2.27, 13.44, -0.04]}
        rotation={[0, 1.13, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line016.geometry}
        material={materials["1"]}
        position={[-5.91, 13.44, -3.85]}
        rotation={[0, 1.13, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/human-stand.gltf");
