/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";

export default function KoncowkaRegalu(props:any) {
  const { nodes, materials } = useGLTF("/models/koncowka-regalu.gltf") as any;
  return (
    <group {...props} dispose={null} position={[0,-0.1,0]}>
      <group
        position={[-0.058, 0.335, 0.059]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line027.geometry}
          material={materials["1.001"]}
          position={[0.591, -0.924, -30.057]}
          rotation={[Math.PI / 2, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line028.geometry}
          material={materials["1.001"]}
          position={[24.228, -7.035, 0.113]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line029.geometry}
          material={materials["1.001"]}
          position={[24.622, -4.861, 0.113]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line030.geometry}
          material={materials["1.001"]}
          position={[-24.228, -7.035, 0.113]}
          rotation={[Math.PI / 2, -1.57, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line031.geometry}
          material={materials["1.001"]}
          position={[-24.622, -4.861, 0.113]}
          rotation={[Math.PI / 2, -1.57, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line032.geometry}
          material={materials["1.001"]}
          position={[-13.782, -15.687, 0.113]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line033.geometry}
          material={materials["1.001"]}
          position={[13.782, -1.791, 0.113]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line034.geometry}
          material={materials["1.001"]}
          position={[1.768, 16.544, 31.19]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line035.geometry}
          material={materials["1.001"]}
          position={[1.022, -1.948, 18.148]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line036.geometry}
          material={materials["1.001"]}
          position={[1.022, -2.107, -17.322]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle0.geometry}
          material={materials["1.001"]}
          position={[1.18, -15.687, 18.159]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle1.geometry}
          material={materials["1.001"]}
          position={[1.172, -15.747, 33.457]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/koncowka-regalu.gltf");