/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";

export default function KoszZasypowy(props:any) {
  const { nodes, materials } = useGLTF("/models/kosz-zasypowy.gltf") as any;
  return (
    <group {...props} dispose={null} position={[0,-0.2,0]}>
      <group
        position={[-0.001, 0.248, 0]}
        rotation={[Math.PI / 2, 0, 0.262]}
        scale={0.01}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001.geometry}
          material={materials["0"]}
          position={[0.122, -8.663, -18.05]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line037.geometry}
          material={materials["0"]}
          position={[0, 0, 24.787]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NGon001.geometry}
          material={materials["0"]}
          position={[0, 0, 24.687]}
          scale={0.726}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NGon004.geometry}
          material={materials["0"]}
          position={[-0.003, 0, 11.441]}
          scale={0.726}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangl10.geometry}
          material={materials["0"]}
          position={[3.801, 0.055, -5.994]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={2.045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangl11.geometry}
          material={materials["0"]}
          position={[7.568, 0.055, -5.994]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={2.045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangl12.geometry}
          material={materials["0"]}
          position={[-5.635, -3.224, -5.994]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={2.045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangl13.geometry}
          material={materials["0"]}
          position={[-1.868, -3.224, -5.994]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={2.045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangl14.geometry}
          material={materials["0"]}
          position={[1.898, -3.224, -5.994]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={2.045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangl15.geometry}
          material={materials["0"]}
          position={[5.665, -3.224, -5.994]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={2.045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangl16.geometry}
          material={materials["0"]}
          position={[-3.732, -6.467, -5.994]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={2.045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangl17.geometry}
          material={materials["0"]}
          position={[0.036, -6.467, -5.994]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={2.045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangl18.geometry}
          material={materials["0"]}
          position={[3.801, -6.467, -5.994]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={2.045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle0.geometry}
          material={materials["0"]}
          position={[3.801, 6.552, -5.994]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={2.045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle1.geometry}
          material={materials["0"]}
          position={[0.036, 6.552, -5.994]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={2.045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle2.geometry}
          material={materials["0"]}
          position={[-3.732, 6.552, -5.994]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={2.045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle3.geometry}
          material={materials["0"]}
          position={[-5.635, 3.274, -5.994]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={2.045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle4.geometry}
          material={materials["0"]}
          position={[-1.868, 3.274, -5.994]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={2.045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle5.geometry}
          material={materials["0"]}
          position={[1.898, 3.274, -5.994]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={2.045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle6.geometry}
          material={materials["0"]}
          position={[5.665, 3.274, -5.994]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={2.045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle7.geometry}
          material={materials["0"]}
          position={[-7.542, 0.055, -5.994]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={2.045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle8.geometry}
          material={materials["0"]}
          position={[-3.732, 0.055, -5.994]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={2.045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle9.geometry}
          material={materials["0"]}
          position={[0.036, 0.055, -5.994]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={2.045}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/kosz-zasypowy.gltf")