/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";

export default function KoszZasyp(props:any) {
  const { nodes, materials } = useGLTF("/models/kosz-zasypowy.gltf") as any;;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={materials.WHITE}
        position={[0.003, 0.7, -0.18]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line037.geometry}
        material={materials.WHITE}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NGon001.geometry}
        material={materials.WHITE}
        scale={0.726}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NGon004.geometry}
        material={materials.WHITE}
        position={[0, 0.28, 0]}
        scale={0.726}
      />
    </group>
  );
}

useGLTF.preload("/models/kosz-zasypowy.gltf");
