/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Krawat(props:any) {
  const { nodes, materials } = useGLTF("models/krawat.gltf") as any;
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, 0.302, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line1235.geometry}
          material={materials["0.001"]}
          position={[-1.33, -1.068, 23.97]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line1236.geometry}
          material={materials["0.001"]}
          position={[-1.33, -1.068, 15.075]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line1237.geometry}
          material={materials["0.001"]}
          position={[-1.33, -1.068, 6.18]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line1238.geometry}
          material={materials["0.001"]}
          position={[-1.33, -1.068, -2.716]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line1239.geometry}
          material={materials["0.001"]}
          position={[-1.33, -1.068, -11.611]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line1240.geometry}
          material={materials["0.001"]}
          position={[-1.33, 0.355, 15.075]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line1241.geometry}
          material={materials["0.001"]}
          position={[-1.33, 0.355, 6.18]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line1242.geometry}
          material={materials["0.001"]}
          position={[-1.33, 0.355, -2.716]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line1243.geometry}
          material={materials["0.001"]}
          position={[-1.33, 0.355, -11.611]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line1244.geometry}
          material={materials["0.001"]}
          position={[-1.33, 0.355, 23.97]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line1245.geometry}
          material={materials["0.001"]}
          position={[-1.33, 1.778, 15.075]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line1246.geometry}
          material={materials["0.001"]}
          position={[-1.33, 1.778, 6.18]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line1247.geometry}
          material={materials["0.001"]}
          position={[-1.33, 1.778, -2.716]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line1248.geometry}
          material={materials["0.001"]}
          position={[-1.33, 1.778, -11.611]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line1249.geometry}
          material={materials["0.001"]}
          position={[-1.33, 1.778, 23.97]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle0.geometry}
          material={materials["0.001"]}
          position={[-1.33, -2.238, 3.872]}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/krawat.gltf");
