/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function ListwaCenowa(props:any) {
  const { nodes, materials } = useGLTF("/models/listwa-cenowa.gltf") as any;
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, -Math.PI / 4]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line006.geometry}
          material={materials["0.002"]}
          position={[9.823, -0.538, 0.011]}
          rotation={[Math.PI / 2, 1.57, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object001.geometry}
          material={materials["0.002"]}
          position={[9.823, -0.538, 0.011]}
          rotation={[Math.PI / 2, 1.57, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/listwa-cenowa.gltf");
