/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function ListwaPolkowa(props:any) {
  const { nodes, materials } = useGLTF("/models/listwa-polkowa.gltf") as any;
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, -Math.PI / 6]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle0.geometry}
          material={materials["0.003"]}
          position={[0.002, 6.937, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle1.geometry}
          material={materials["0.003"]}
          position={[0.002, 6.803, 7.453]}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/listwa-polkowa.gltf");
