/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";

export default function ObudowaSlupa(props:any) {
  const { nodes, materials } = useGLTF("/models/obudowa-slupa.gltf") as any;
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.099, 0.63, -0.032]}
        rotation={[Math.PI / 2, 0, -0.611]}
        scale={0.01}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line055.geometry}
          material={materials["0.004"]}
          position={[5.719, 19.254, 24.326]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line056.geometry}
          material={materials["0.004"]}
          position={[12.185, 19.3, 24.326]}
          rotation={[Math.PI / 2, 1.571, 0]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line057.geometry}
          material={materials["0.004"]}
          position={[5.512, 19.254, 24.326]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line058.geometry}
          material={materials["0.004"]}
          position={[11.849, 19.254, 24.326]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line059.geometry}
          material={materials["0.004"]}
          position={[11.844, 19.541, 10.042]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line060.geometry}
          material={materials["0.004"]}
          position={[5.28, 19.254, 24.326]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line061.geometry}
          material={materials["0.004"]}
          position={[-1.186, 19.3, 24.326]}
          rotation={[Math.PI / 2, -1.57, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line062.geometry}
          material={materials["0.004"]}
          position={[5.487, 19.254, 24.326]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line063.geometry}
          material={materials["0.004"]}
          position={[-0.85, 19.254, 24.326]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line064.geometry}
          material={materials["0.004"]}
          position={[-0.845, 19.541, 10.042]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line072.geometry}
          material={materials["0.004"]}
          position={[-7.184, 19.194, 24.326]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line078.geometry}
          material={materials["0.004"]}
          position={[-7.437, -2.964, 22.959]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line079.geometry}
          material={materials["0.004"]}
          position={[-7.409, -2.964, 62.992]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LODÓWKA001.geometry}
          material={materials["0.004"]}
          position={[17.07, 3.701, 62.992]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object001.geometry}
          material={materials["0.004"]}
          position={[-22.635, -5.783, 62.992]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003.geometry}
          material={materials["0.004"]}
          position={[-16.995, 19.197, 54.613]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004.geometry}
          material={materials["0.004"]}
          position={[5.442, 19.197, 54.613]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangl10.geometry}
          material={materials["0.004"]}
          position={[-5.757, -11.97, 58.145]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangl11.geometry}
          material={materials["0.004"]}
          position={[-6.664, 14.158, 23.404]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangl12.geometry}
          material={materials["0.004"]}
          position={[-4.195, 4.011, 62.992]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle0.geometry}
          material={materials["0.004"]}
          position={[4.563, -17.073, 62.992]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle1.geometry}
          material={materials["0.004"]}
          position={[11.546, 17.299, 54.697]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle2.geometry}
          material={materials["0.004"]}
          position={[-16.273, 19.297, 54.582]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle3.geometry}
          material={materials["0.004"]}
          position={[5.569, 19.297, 54.582]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle4.geometry}
          material={materials["0.004"]}
          position={[8.766, 22.948, 43.6]}
          rotation={[1.92, 0, 0]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle5.geometry}
          material={materials["0.004"]}
          position={[-4.402, 3.764, -23.622]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle6.geometry}
          material={materials["0.004"]}
          position={[8.478, -8.06, 28.654]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle7.geometry}
          material={materials["0.004"]}
          position={[-22.635, -5.783, 62.992]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle8.geometry}
          material={materials["0.004"]}
          position={[16.607, 14.142, 6.541]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle9.geometry}
          material={materials["0.004"]}
          position={[24.167, 14.158, 46.913]}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/obudowa-slupa.gltf");
