/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Shelfstoper(props:any) {
  const { nodes, materials } = useGLTF("/models/shelfstoper.gltf") as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SHELFSTOPE.geometry}
        material={materials["0.007"]}
        position={[0.002, 0.007, 0.003]}
        rotation={[-Math.PI, Math.PI / 4, 0]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/models/shelfstoper.gltf");
