/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";

export default function StandK(props:any) {
  const { nodes, materials } = useGLTF("/models/stand-karton.gltf") as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rectangle0.geometry}
        material={materials.WHITE}
        position={[0, 0.414, -0.003]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.561}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rectangle1.geometry}
        material={materials.WHITE}
        position={[0, 0.641, -0.01]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.561}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rectangle2.geometry}
        material={materials.WHITE}
        position={[0, 0.86, -0.035]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.561}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rectangle3.geometry}
        material={materials.WHITE}
        position={[0.195, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rectangle4.geometry}
        material={materials.WHITE}
        position={[0, 1.082, -0.035]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.561}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rectangle5.geometry}
        material={materials.WHITE}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Shape006.geometry}
        material={materials.WHITE}
        position={[0.001, 0.197, -0.145]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.561}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Shape008.geometry}
        material={materials.WHITE}
        position={[0.001, 1.12, -0.145]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.561}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Shape009.geometry}
        material={materials.WHITE}
        position={[0, 0.001, 0.126]}
        rotation={[1.484, 0, 0]}
        scale={1.561}
      />
    </group>
  );
}

useGLTF.preload("/models/stand-karton.gltf");
