/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Stand(props:any) {
  const { nodes, materials } = useGLTF("/models/stand-wolnostojacy.gltf") as any;
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0.455]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3458.geometry}
          material={materials["0.009"]}
          position={[-9.272, 4.302, -4.55]}
          rotation={[Math.PI / 2, 1.57, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3459.geometry}
          material={materials["0.009"]}
          position={[-0.15, 1.739, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3460.geometry}
          material={materials["0.009"]}
          position={[5.976, 6.897, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3461.geometry}
          material={materials["0.009"]}
          position={[-9.738, 7.023, 25.238]}
          rotation={[1.666, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3462.geometry}
          material={materials["0.009"]}
          position={[-6.35, 6.897, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3463.geometry}
          material={materials["0.009"]}
          position={[-6.35, 5.557, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3464.geometry}
          material={materials["0.009"]}
          position={[-2.242, 4.216, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3465.geometry}
          material={materials["0.009"]}
          position={[5.976, -6.507, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3466.geometry}
          material={materials["0.009"]}
          position={[-6.35, -6.507, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3467.geometry}
          material={materials["0.009"]}
          position={[-2.242, -6.507, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3468.geometry}
          material={materials["0.009"]}
          position={[1.867, -6.507, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3469.geometry}
          material={materials["0.009"]}
          position={[5.976, -5.167, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3470.geometry}
          material={materials["0.009"]}
          position={[-6.35, -5.167, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3471.geometry}
          material={materials["0.009"]}
          position={[-2.242, -5.167, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3472.geometry}
          material={materials["0.009"]}
          position={[1.867, -5.167, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3473.geometry}
          material={materials["0.009"]}
          position={[5.976, -3.826, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3474.geometry}
          material={materials["0.009"]}
          position={[-6.35, -3.826, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3475.geometry}
          material={materials["0.009"]}
          position={[-2.242, -3.826, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3476.geometry}
          material={materials["0.009"]}
          position={[1.867, -3.826, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3477.geometry}
          material={materials["0.009"]}
          position={[-6.35, 4.216, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3478.geometry}
          material={materials["0.009"]}
          position={[-6.35, -2.486, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3479.geometry}
          material={materials["0.009"]}
          position={[-2.242, -2.486, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3480.geometry}
          material={materials["0.009"]}
          position={[1.867, -2.486, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3481.geometry}
          material={materials["0.009"]}
          position={[-2.242, 2.876, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3482.geometry}
          material={materials["0.009"]}
          position={[-6.35, -1.146, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3483.geometry}
          material={materials["0.009"]}
          position={[-2.242, -1.146, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3484.geometry}
          material={materials["0.009"]}
          position={[1.867, -1.146, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3485.geometry}
          material={materials["0.009"]}
          position={[-6.35, 2.876, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3486.geometry}
          material={materials["0.009"]}
          position={[-6.35, 0.195, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3487.geometry}
          material={materials["0.009"]}
          position={[-2.242, 0.195, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3488.geometry}
          material={materials["0.009"]}
          position={[1.867, 0.195, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3489.geometry}
          material={materials["0.009"]}
          position={[-2.242, 1.535, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3490.geometry}
          material={materials["0.009"]}
          position={[-6.35, 1.535, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3491.geometry}
          material={materials["0.009"]}
          position={[5.976, 1.535, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3492.geometry}
          material={materials["0.009"]}
          position={[1.867, 1.535, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3493.geometry}
          material={materials["0.009"]}
          position={[5.976, 2.876, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3494.geometry}
          material={materials["0.009"]}
          position={[5.976, 0.195, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3495.geometry}
          material={materials["0.009"]}
          position={[5.976, -1.146, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3496.geometry}
          material={materials["0.009"]}
          position={[1.867, 2.876, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3497.geometry}
          material={materials["0.009"]}
          position={[5.976, 4.216, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3498.geometry}
          material={materials["0.009"]}
          position={[5.976, -2.486, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3499.geometry}
          material={materials["0.009"]}
          position={[1.867, 4.216, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3500.geometry}
          material={materials["0.009"]}
          position={[5.976, 5.557, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3501.geometry}
          material={materials["0.009"]}
          position={[-2.242, 5.557, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3502.geometry}
          material={materials["0.009"]}
          position={[1.867, 5.557, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3503.geometry}
          material={materials["0.009"]}
          position={[-0.844, 7.875, -26.943]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3504.geometry}
          material={materials["0.009"]}
          position={[-2.242, 6.897, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3505.geometry}
          material={materials["0.009"]}
          position={[1.867, 6.897, 19.152]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3506.geometry}
          material={materials["0.009"]}
          position={[-9.748, 4.302, -4.55]}
          rotation={[Math.PI / 2, 1.57, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3507.geometry}
          material={materials["0.009"]}
          position={[8.756, 4.302, -4.55]}
          rotation={[Math.PI / 2, 1.57, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3508.geometry}
          material={materials["0.009"]}
          position={[-3.429, -2.84, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3509.geometry}
          material={materials["0.009"]}
          position={[-6.708, 6.034, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3510.geometry}
          material={materials["0.009"]}
          position={[-6.708, 5.227, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3511.geometry}
          material={materials["0.009"]}
          position={[-6.708, 4.421, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3512.geometry}
          material={materials["0.009"]}
          position={[-6.708, 3.614, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3513.geometry}
          material={materials["0.009"]}
          position={[-6.708, 2.807, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3514.geometry}
          material={materials["0.009"]}
          position={[-6.708, 2.001, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3515.geometry}
          material={materials["0.009"]}
          position={[-6.708, 1.194, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3516.geometry}
          material={materials["0.009"]}
          position={[-6.708, 0.388, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3517.geometry}
          material={materials["0.009"]}
          position={[-6.708, -0.419, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3518.geometry}
          material={materials["0.009"]}
          position={[-6.708, -1.225, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3519.geometry}
          material={materials["0.009"]}
          position={[-6.708, -2.032, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3520.geometry}
          material={materials["0.009"]}
          position={[-3.429, 6.034, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3521.geometry}
          material={materials["0.009"]}
          position={[-3.429, 5.227, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3522.geometry}
          material={materials["0.009"]}
          position={[-3.429, 4.421, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3523.geometry}
          material={materials["0.009"]}
          position={[-3.429, 3.614, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3524.geometry}
          material={materials["0.009"]}
          position={[-3.429, 2.807, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3525.geometry}
          material={materials["0.009"]}
          position={[-3.429, 2.001, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3526.geometry}
          material={materials["0.009"]}
          position={[-3.429, 1.194, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3527.geometry}
          material={materials["0.009"]}
          position={[-3.429, 0.388, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3528.geometry}
          material={materials["0.009"]}
          position={[-3.429, -0.419, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3529.geometry}
          material={materials["0.009"]}
          position={[-3.429, -1.225, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3530.geometry}
          material={materials["0.009"]}
          position={[-3.429, -2.032, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3531.geometry}
          material={materials["0.009"]}
          position={[-0.15, 6.034, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3532.geometry}
          material={materials["0.009"]}
          position={[-0.15, 5.227, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3533.geometry}
          material={materials["0.009"]}
          position={[-0.15, 4.421, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3534.geometry}
          material={materials["0.009"]}
          position={[-0.15, 3.614, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3535.geometry}
          material={materials["0.009"]}
          position={[-0.15, 2.808, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3536.geometry}
          material={materials["0.009"]}
          position={[-0.15, 2.001, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3537.geometry}
          material={materials["0.009"]}
          position={[-0.15, 1.194, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3538.geometry}
          material={materials["0.009"]}
          position={[-0.15, 0.388, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3539.geometry}
          material={materials["0.009"]}
          position={[-0.15, -0.419, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3540.geometry}
          material={materials["0.009"]}
          position={[-0.15, -1.225, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3541.geometry}
          material={materials["0.009"]}
          position={[-0.15, -2.032, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3542.geometry}
          material={materials["0.009"]}
          position={[3.13, 6.034, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3543.geometry}
          material={materials["0.009"]}
          position={[3.13, 5.227, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3544.geometry}
          material={materials["0.009"]}
          position={[3.13, 4.421, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3545.geometry}
          material={materials["0.009"]}
          position={[3.13, 3.614, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3546.geometry}
          material={materials["0.009"]}
          position={[3.13, 2.807, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3547.geometry}
          material={materials["0.009"]}
          position={[3.13, 2.001, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3548.geometry}
          material={materials["0.009"]}
          position={[3.13, 1.194, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3549.geometry}
          material={materials["0.009"]}
          position={[3.13, 0.388, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3550.geometry}
          material={materials["0.009"]}
          position={[3.13, -0.419, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3551.geometry}
          material={materials["0.009"]}
          position={[3.13, -1.225, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3552.geometry}
          material={materials["0.009"]}
          position={[3.13, -2.032, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3553.geometry}
          material={materials["0.009"]}
          position={[6.409, 6.034, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3554.geometry}
          material={materials["0.009"]}
          position={[6.409, 5.227, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3555.geometry}
          material={materials["0.009"]}
          position={[6.409, 4.421, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3556.geometry}
          material={materials["0.009"]}
          position={[6.409, 3.614, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3557.geometry}
          material={materials["0.009"]}
          position={[6.409, 2.807, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3558.geometry}
          material={materials["0.009"]}
          position={[6.409, 2.001, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3559.geometry}
          material={materials["0.009"]}
          position={[6.409, 1.194, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3560.geometry}
          material={materials["0.009"]}
          position={[6.409, 0.388, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3561.geometry}
          material={materials["0.009"]}
          position={[6.409, -0.419, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3562.geometry}
          material={materials["0.009"]}
          position={[6.409, -1.225, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3563.geometry}
          material={materials["0.009"]}
          position={[6.409, -2.032, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3564.geometry}
          material={materials["0.009"]}
          position={[-3.429, -4.453, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3565.geometry}
          material={materials["0.009"]}
          position={[-0.15, -4.453, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3566.geometry}
          material={materials["0.009"]}
          position={[3.13, -4.453, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3567.geometry}
          material={materials["0.009"]}
          position={[6.409, -4.453, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3568.geometry}
          material={materials["0.009"]}
          position={[-6.708, -4.453, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3569.geometry}
          material={materials["0.009"]}
          position={[-6.708, -2.84, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3570.geometry}
          material={materials["0.009"]}
          position={[-6.708, -3.646, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3571.geometry}
          material={materials["0.009"]}
          position={[-3.429, -3.646, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3572.geometry}
          material={materials["0.009"]}
          position={[-0.15, -2.84, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3573.geometry}
          material={materials["0.009"]}
          position={[-0.15, -3.646, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3574.geometry}
          material={materials["0.009"]}
          position={[3.13, -2.84, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3575.geometry}
          material={materials["0.009"]}
          position={[3.13, -3.646, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3576.geometry}
          material={materials["0.009"]}
          position={[6.409, -2.84, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3577.geometry}
          material={materials["0.009"]}
          position={[6.409, -3.646, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3578.geometry}
          material={materials["0.009"]}
          position={[-3.429, -5.247, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3579.geometry}
          material={materials["0.009"]}
          position={[-0.15, -5.247, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3580.geometry}
          material={materials["0.009"]}
          position={[3.13, -5.247, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3581.geometry}
          material={materials["0.009"]}
          position={[6.409, -5.247, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3582.geometry}
          material={materials["0.009"]}
          position={[-6.708, -5.247, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3583.geometry}
          material={materials["0.009"]}
          position={[-3.429, -6.04, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3584.geometry}
          material={materials["0.009"]}
          position={[-0.15, -6.04, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3585.geometry}
          material={materials["0.009"]}
          position={[3.13, -6.04, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3586.geometry}
          material={materials["0.009"]}
          position={[6.409, -6.04, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3587.geometry}
          material={materials["0.009"]}
          position={[-6.708, -6.04, 7.188]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3588.geometry}
          material={materials["0.009"]}
          position={[-3.429, -2.84, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3589.geometry}
          material={materials["0.009"]}
          position={[-6.708, 5.227, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3590.geometry}
          material={materials["0.009"]}
          position={[-6.708, 4.421, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3591.geometry}
          material={materials["0.009"]}
          position={[-6.708, 3.614, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3592.geometry}
          material={materials["0.009"]}
          position={[-6.708, 2.807, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3593.geometry}
          material={materials["0.009"]}
          position={[-6.708, 2.001, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3594.geometry}
          material={materials["0.009"]}
          position={[-6.708, 1.194, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3595.geometry}
          material={materials["0.009"]}
          position={[-6.708, 0.388, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3596.geometry}
          material={materials["0.009"]}
          position={[-6.708, -0.419, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3597.geometry}
          material={materials["0.009"]}
          position={[-6.708, -1.225, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3598.geometry}
          material={materials["0.009"]}
          position={[-6.708, -2.032, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3599.geometry}
          material={materials["0.009"]}
          position={[-3.429, 5.227, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3600.geometry}
          material={materials["0.009"]}
          position={[-3.429, 4.421, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3601.geometry}
          material={materials["0.009"]}
          position={[-3.429, 3.614, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3602.geometry}
          material={materials["0.009"]}
          position={[-3.429, 2.807, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3603.geometry}
          material={materials["0.009"]}
          position={[-3.429, 2.001, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3604.geometry}
          material={materials["0.009"]}
          position={[-3.429, 1.194, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3605.geometry}
          material={materials["0.009"]}
          position={[-3.429, 0.388, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3606.geometry}
          material={materials["0.009"]}
          position={[-3.429, -0.419, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3607.geometry}
          material={materials["0.009"]}
          position={[-3.429, -1.225, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3608.geometry}
          material={materials["0.009"]}
          position={[-3.429, -2.032, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3609.geometry}
          material={materials["0.009"]}
          position={[-0.15, 5.227, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3610.geometry}
          material={materials["0.009"]}
          position={[-0.15, 4.421, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3611.geometry}
          material={materials["0.009"]}
          position={[-0.15, 3.614, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3612.geometry}
          material={materials["0.009"]}
          position={[-0.15, 2.808, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3613.geometry}
          material={materials["0.009"]}
          position={[-0.15, 2.001, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3614.geometry}
          material={materials["0.009"]}
          position={[-0.15, 1.194, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3615.geometry}
          material={materials["0.009"]}
          position={[-0.15, 0.388, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3616.geometry}
          material={materials["0.009"]}
          position={[-0.15, -0.419, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3617.geometry}
          material={materials["0.009"]}
          position={[-0.15, -1.225, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3618.geometry}
          material={materials["0.009"]}
          position={[-0.15, -2.032, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3619.geometry}
          material={materials["0.009"]}
          position={[-3.429, -4.453, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3620.geometry}
          material={materials["0.009"]}
          position={[-0.15, -4.453, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3621.geometry}
          material={materials["0.009"]}
          position={[-6.708, -4.453, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3622.geometry}
          material={materials["0.009"]}
          position={[-6.708, -2.84, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3623.geometry}
          material={materials["0.009"]}
          position={[-6.708, -3.646, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3624.geometry}
          material={materials["0.009"]}
          position={[-3.429, -3.646, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3625.geometry}
          material={materials["0.009"]}
          position={[-0.15, -2.84, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3626.geometry}
          material={materials["0.009"]}
          position={[-0.15, -3.646, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3627.geometry}
          material={materials["0.009"]}
          position={[-3.429, -5.247, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3628.geometry}
          material={materials["0.009"]}
          position={[-0.15, -5.247, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3629.geometry}
          material={materials["0.009"]}
          position={[-6.708, -5.247, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3630.geometry}
          material={materials["0.009"]}
          position={[3.13, 5.227, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3631.geometry}
          material={materials["0.009"]}
          position={[3.13, 4.421, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3632.geometry}
          material={materials["0.009"]}
          position={[3.13, 3.614, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3633.geometry}
          material={materials["0.009"]}
          position={[3.13, 2.807, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3634.geometry}
          material={materials["0.009"]}
          position={[3.13, 2.001, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3635.geometry}
          material={materials["0.009"]}
          position={[3.13, 1.194, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3636.geometry}
          material={materials["0.009"]}
          position={[3.13, 0.388, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3637.geometry}
          material={materials["0.009"]}
          position={[3.13, -0.419, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3638.geometry}
          material={materials["0.009"]}
          position={[3.13, -1.225, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3639.geometry}
          material={materials["0.009"]}
          position={[3.13, -2.032, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3640.geometry}
          material={materials["0.009"]}
          position={[6.409, 5.227, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3641.geometry}
          material={materials["0.009"]}
          position={[6.409, 4.421, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3642.geometry}
          material={materials["0.009"]}
          position={[6.409, 3.614, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3643.geometry}
          material={materials["0.009"]}
          position={[6.409, 2.807, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3644.geometry}
          material={materials["0.009"]}
          position={[6.409, 2.001, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3645.geometry}
          material={materials["0.009"]}
          position={[6.409, 1.194, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3646.geometry}
          material={materials["0.009"]}
          position={[6.409, 0.388, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3647.geometry}
          material={materials["0.009"]}
          position={[6.409, -0.419, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3648.geometry}
          material={materials["0.009"]}
          position={[6.409, -1.225, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3649.geometry}
          material={materials["0.009"]}
          position={[6.409, -2.032, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3650.geometry}
          material={materials["0.009"]}
          position={[3.13, -4.453, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3651.geometry}
          material={materials["0.009"]}
          position={[6.409, -4.453, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3652.geometry}
          material={materials["0.009"]}
          position={[3.13, -2.84, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3653.geometry}
          material={materials["0.009"]}
          position={[3.13, -3.646, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3654.geometry}
          material={materials["0.009"]}
          position={[6.409, -2.84, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3655.geometry}
          material={materials["0.009"]}
          position={[6.409, -3.646, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3656.geometry}
          material={materials["0.009"]}
          position={[3.13, -5.247, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3657.geometry}
          material={materials["0.009"]}
          position={[6.409, -5.247, -1.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3658.geometry}
          material={materials["0.009"]}
          position={[-9.738, -7.057, 25.238]}
          rotation={[1.476, 1.57, 0]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3659.geometry}
          material={materials["0.009"]}
          position={[-0.844, -7.891, -26.943]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3660.geometry}
          material={materials["0.009"]}
          position={[-9.553, 7.091, -27.658]}
          rotation={[Math.PI / 2, 1.57, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3661.geometry}
          material={materials["0.009"]}
          position={[9.561, 7.091, -27.658]}
          rotation={[Math.PI / 2, 1.57, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3662.geometry}
          material={materials["0.009"]}
          position={[-3.429, -3.102, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3663.geometry}
          material={materials["0.009"]}
          position={[-6.708, 4.159, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3664.geometry}
          material={materials["0.009"]}
          position={[-6.708, 3.352, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3665.geometry}
          material={materials["0.009"]}
          position={[-6.708, 2.546, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3666.geometry}
          material={materials["0.009"]}
          position={[-6.708, 1.739, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3667.geometry}
          material={materials["0.009"]}
          position={[-6.708, 0.933, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3668.geometry}
          material={materials["0.009"]}
          position={[-6.708, 0.126, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3669.geometry}
          material={materials["0.009"]}
          position={[-6.708, -0.681, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3670.geometry}
          material={materials["0.009"]}
          position={[-6.708, -1.487, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3671.geometry}
          material={materials["0.009"]}
          position={[-6.708, -2.294, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3672.geometry}
          material={materials["0.009"]}
          position={[-3.429, 4.159, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3673.geometry}
          material={materials["0.009"]}
          position={[-3.429, 3.352, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3674.geometry}
          material={materials["0.009"]}
          position={[-3.429, 2.546, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3675.geometry}
          material={materials["0.009"]}
          position={[-3.429, 1.739, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3676.geometry}
          material={materials["0.009"]}
          position={[-3.429, 0.933, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3677.geometry}
          material={materials["0.009"]}
          position={[-3.429, 0.126, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3678.geometry}
          material={materials["0.009"]}
          position={[-3.429, -0.681, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3679.geometry}
          material={materials["0.009"]}
          position={[-3.429, -1.487, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3680.geometry}
          material={materials["0.009"]}
          position={[-3.429, -2.294, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3681.geometry}
          material={materials["0.009"]}
          position={[-0.15, 4.159, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3682.geometry}
          material={materials["0.009"]}
          position={[-0.15, 3.352, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3683.geometry}
          material={materials["0.009"]}
          position={[-0.15, 2.546, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3684.geometry}
          material={materials["0.009"]}
          position={[-0.15, 0.933, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3685.geometry}
          material={materials["0.009"]}
          position={[-0.15, 0.126, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3686.geometry}
          material={materials["0.009"]}
          position={[-0.15, -0.681, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3687.geometry}
          material={materials["0.009"]}
          position={[-0.15, -1.487, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3688.geometry}
          material={materials["0.009"]}
          position={[-0.15, -2.294, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3689.geometry}
          material={materials["0.009"]}
          position={[-6.708, -3.102, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3690.geometry}
          material={materials["0.009"]}
          position={[-6.708, -3.908, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3691.geometry}
          material={materials["0.009"]}
          position={[-3.429, -3.908, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3692.geometry}
          material={materials["0.009"]}
          position={[-0.15, -3.102, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3693.geometry}
          material={materials["0.009"]}
          position={[-0.15, -3.908, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3694.geometry}
          material={materials["0.009"]}
          position={[3.13, 4.159, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3695.geometry}
          material={materials["0.009"]}
          position={[3.13, 3.352, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3696.geometry}
          material={materials["0.009"]}
          position={[3.13, 2.546, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3697.geometry}
          material={materials["0.009"]}
          position={[3.13, 1.739, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3698.geometry}
          material={materials["0.009"]}
          position={[3.13, 0.933, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3699.geometry}
          material={materials["0.009"]}
          position={[3.13, 0.126, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3700.geometry}
          material={materials["0.009"]}
          position={[3.13, -0.681, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3701.geometry}
          material={materials["0.009"]}
          position={[3.13, -1.487, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3702.geometry}
          material={materials["0.009"]}
          position={[3.13, -2.294, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3703.geometry}
          material={materials["0.009"]}
          position={[6.409, 4.159, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3704.geometry}
          material={materials["0.009"]}
          position={[6.409, 3.352, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3705.geometry}
          material={materials["0.009"]}
          position={[6.409, 2.546, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3706.geometry}
          material={materials["0.009"]}
          position={[6.409, 1.739, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3707.geometry}
          material={materials["0.009"]}
          position={[6.409, 0.933, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3708.geometry}
          material={materials["0.009"]}
          position={[6.409, 0.126, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3709.geometry}
          material={materials["0.009"]}
          position={[6.409, -0.681, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3710.geometry}
          material={materials["0.009"]}
          position={[6.409, -1.487, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3711.geometry}
          material={materials["0.009"]}
          position={[6.409, -2.294, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3712.geometry}
          material={materials["0.009"]}
          position={[3.13, -3.102, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3713.geometry}
          material={materials["0.009"]}
          position={[3.13, -3.908, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3714.geometry}
          material={materials["0.009"]}
          position={[6.409, -3.102, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3715.geometry}
          material={materials["0.009"]}
          position={[6.409, -3.908, -10.511]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.821, 0.602, 0.602]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3716.geometry}
          material={materials["0.009"]}
          position={[9.241, 4.302, -4.55]}
          rotation={[Math.PI / 2, 1.57, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3717.geometry}
          material={materials["0.009"]}
          position={[-9.25, 4.302, -4.55]}
          rotation={[Math.PI / 2, 1.57, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3718.geometry}
          material={materials["0.009"]}
          position={[9.014, 4.302, -4.55]}
          rotation={[Math.PI / 2, -1.571, 0]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object013.geometry}
          material={materials["0.009"]}
          position={[-0.844, 7.877, -26.943]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object014.geometry}
          material={materials["0.009"]}
          position={[-0.844, -8.089, -26.943]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-1, 1, 2.097]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangl10.geometry}
          material={materials["0.009"]}
          position={[-0.115, 0.02, -11.297]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle0.geometry}
          material={materials["0.009"]}
          position={[-8.951, -0.013, 31.695]}
          rotation={[Math.PI / 2, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle1.geometry}
          material={materials["0.009"]}
          position={[-0.092, -6.903, 7.413]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle2.geometry}
          material={materials["0.009"]}
          position={[9.542, -0.013, 31.695]}
          rotation={[Math.PI / 2, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle3.geometry}
          material={materials["0.009"]}
          position={[-8.951, -0.013, 31.695]}
          rotation={[Math.PI / 2, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle4.geometry}
          material={materials["0.009"]}
          position={[-0.092, 7.609, 18.157]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle5.geometry}
          material={materials["0.009"]}
          position={[-8.951, 2.496, -0.088]}
          rotation={[1.423, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle6.geometry}
          material={materials["0.009"]}
          position={[-0.092, -7.887, 19.374]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle7.geometry}
          material={materials["0.009"]}
          position={[-8.951, -2.565, -0.088]}
          rotation={[1.719, 1.57, 0]}
          scale={[-1, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle8.geometry}
          material={materials["0.009"]}
          position={[-0.115, 0.02, 6.399]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle9.geometry}
          material={materials["0.009"]}
          position={[-0.115, 0.02, -1.95]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/stand-wolnostojacy.gltf");
