/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Toper(props:any) {
  const { nodes, materials } = useGLTF("/models/toper.gltf") as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials["0.010"]}
        position={[0, 0.219, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Shape004.geometry}
        material={materials["0.010"]}
        position={[-0.008, 0.362, -0.003]}
        rotation={[-Math.PI, 0.436, -0.087]}
        scale={[-0.114, 0.114, 0.114]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Shape1.geometry}
        material={materials["0.010"]}
        position={[-0.011, 0.351, 0.005]}
        rotation={[-Math.PI, 0.436, 0]}
        scale={0.09}
      />
    </group>
  );
}

useGLTF.preload("/models/toper.gltf");
