/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Wobler(props:any) {
  const { nodes, materials } = useGLTF("/models/wobler.gltf") as any;
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, -Math.PI / 4]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle003.geometry}
          material={materials["0.011"]}
          position={[0.017, -1.146, -0.365]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Helix001.geometry}
          material={materials["0.011"]}
          position={[0.016, 0.76, -0.364]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape003.geometry}
          material={materials["0.011"]}
          position={[-0.003, 0.804, -0.376]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.393}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape007.geometry}
          material={materials["0.011"]}
          position={[-0.002, 0.791, -0.376]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.393}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape008.geometry}
          material={materials["0.011"]}
          position={[-0.002, 1.131, -0.376]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.393}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/wobler.gltf");
