/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function WyspaPaletowa(props:any) {
  const { nodes, materials } = useGLTF("/models/wyspa-paletowa.gltf") as any;
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.048, 0.306, -0.001]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box01.geometry}
          material={materials["1.001"]}
          position={[17.918, 26.883, 1.033]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box02.geometry}
          material={materials["1.001"]}
          position={[17.918, 26.883, -11.906]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line01.geometry}
          material={materials["1.001"]}
          position={[1.087, 3.622, 30.603]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line03.geometry}
          material={materials["1.001"]}
          position={[22.897, 33.706, 13.528]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[-1.076, 1.076, 1.076]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line04.geometry}
          material={materials["1.001"]}
          position={[-22.145, -33.635, 13.528]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-1.076, 1.076, 1.076]}
        />
        <group position={[0.122, -19.394, 11.664]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectang217.geometry}
            material={materials["1.001"]}
            position={[25.659, -5.813, 18.939]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object01.geometry}
          material={materials["1.001"]}
          position={[-11.673, 2.199, 29.816]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object02.geometry}
          material={materials["1.001"]}
          position={[12.024, -2.216, 29.816]}
          rotation={[0, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectang127.geometry}
          material={materials["1.001"]}
          position={[-19.558, 20.98, -20.952]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={1.282}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectang128.geometry}
          material={materials["1.001"]}
          position={[28.021, 5.938, 28.585]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectang129.geometry}
          material={materials["1.001"]}
          position={[-28.021, -5.797, 28.585]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangl30.geometry}
          material={materials["1.001"]}
          position={[-2.83, -13.582, 29.816]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangl31.geometry}
          material={materials["1.001"]}
          position={[10.478, 21.371, 12.343]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangl32.geometry}
          material={materials["1.001"]}
          position={[1.284, 20.946, -4.835]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={0.589}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangl33.geometry}
          material={materials["1.001"]}
          position={[2.997, 26.883, -12.018]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangl57.geometry}
          material={materials["1.001"]}
          position={[-22.942, 32.776, -20.844]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.748, 0.849, 0.849]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangl58.geometry}
          material={materials["1.001"]}
          position={[19.427, 32.721, -20.952]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={1.282}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangl59.geometry}
          material={materials["1.001"]}
          position={[2.999, 26.888, -21.911]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangl60.geometry}
          material={materials["1.001"]}
          position={[-26.275, 1.916, 30.603]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangl61.geometry}
          material={materials["1.001"]}
          position={[2.847, 17.511, 29.816]}
          rotation={[0, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangl62.geometry}
          material={materials["1.001"]}
          position={[-3.254, 34.988, 28.585]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangl63.geometry}
          material={materials["1.001"]}
          position={[-3.164, -34.988, 28.585]}
          rotation={[0, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangl64.geometry}
          material={materials["1.001"]}
          position={[2.997, 26.883, 0.926]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangl65.geometry}
          material={materials["1.001"]}
          position={[2.997, 26.883, -21.91]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangl66.geometry}
          material={materials["1.001"]}
          position={[2.997, 26.883, -30.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape01.geometry}
          material={materials["1.001"]}
          position={[25.571, 25.195, -0.961]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[-0.73, 0.73, 0.73]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape02.geometry}
          material={materials["1.001"]}
          position={[-26.08, 25.195, -0.961]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[-0.73, 0.73, 0.73]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/wyspa-paletowa.gltf");
